Kiralama/Kiralama/Controllers/FilmlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kiralama.Data;
using Kiralama.Models;

namespace Kiralama.Controllers
{
    public class FilmlerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public FilmlerController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Filmler
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                return View("AdminIndex",await _context.Filmler.ToListAsync());
            }
            else
            {
                return View("Index",await _context.Filmler.ToListAsync());
            }
            
        }

        // GET: Filmler/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmler = await _context.Filmler
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filmler == null)
            {
                return NotFound();
            }

            return View(filmler);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Filmler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FilmAdi,ResimYolu,Tur,Dil,Sure,Aciklama,Yonetmen,Oyuncular,KiralamaUcreti")] Filmler filmler)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filmler);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filmler);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmler = await _context.Filmler.FindAsync(id);
            if (filmler == null)
            {
                return NotFound();
            }
            return View(filmler);
        }

        // POST: Filmler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FilmAdi,ResimYolu,Tur,Dil,Sure,Aciklama,Yonetmen,Oyuncular,KiralamaUcreti")] Filmler filmler)
        {
            if (id != filmler.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filmler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmlerExists(filmler.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filmler);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmler = await _context.Filmler
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filmler == null)
            {
                return NotFound();
            }

            return View(filmler);
        }

        // POST: Filmler/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filmler = await _context.Filmler.FindAsync(id);
            _context.Filmler.Remove(filmler);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmlerExists(int id)
        {
            return _context.Filmler.Any(e => e.Id == id);
        }
        [Authorize]
        public async Task<IActionResult> Kirala(int? id)
        {
            Filmler film = _context.Filmler.Find(id);
            SatinAlma sta = new SatinAlma();
            if (_userManager.GetUserId(HttpContext.User) != null)
            {
                var userN = _userManager.GetUserId(HttpContext.User);
                Guid userGuid = Guid.Parse(userN);
                sta.FilmID = film.Id;
                sta.UserID = userGuid;

                bool asd = false;
                var purchaseIdList = _context.SatinAlma.Where(q => q.UserID == userGuid).Select(q => q.FilmID).ToList();
                foreach (var item in purchaseIdList)
                {
                    asd = purchaseIdList.Contains(film.Id);
                }

                if (asd == false)
                {
                    _context.Add(sta);
                    await _context.SaveChangesAsync();
                    RedirectToAction("Index");
                }
                else
                {
                    RedirectToAction("Error", "Home");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

Kiralama/Kiralama/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}



<br /><br />
      <div class="container" style="padding:5%;text-align:center">

          <div class="text-danger" asp-validation-summary="All"></div>
          <h2>Bu alana erişemezsiniz.</h2>
          <br />

          <br />
          <h5> Bu ürün size ait değil. <a asp-action="Login" asp-controller="Account"> Giriş yapabilirsiniz.</a></h5>
          <br />





          <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
      </div>

Kiralama/Kiralama/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Abstergo Film Kiralama</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <LINK REL="SHORTCUT ICON"
          HREF="~/images/abstergologo.png">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="padding-top:10px;"><img src="~/images/pngbarn2.png" height="30" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li><a asp-area="" asp-controller="Filmler" asp-action="Index">Filmler</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Filmlerim">Hesabım</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">İletişim</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Hakkımızda</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Abstergo - Bütün hakları saklıdır.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>